version: 2.1
orbs:
  alcide: alcideio/alcide-advisor@dev:0.0.1

workflows:
  advisor_scan:
    jobs:
      - alcide/advisor_scan:
          #cluster_context: 'myclustercontext'
          report_format: 'html'
          fail_on_critical: false
          alcide_apiserver: ''
          policy_profile: ''